
services:
  php:
    container_name: ${APP_NAME}
    build:
      context: php
      dockerfile: ./php-fpm.Dockerfile
      target: base
    networks:
      - project_net

  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}_mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - project_net
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    image: nginx:latest
    container_name: ${APP_NAME}_nginx
    networks:
      - project_net

networks:
  project_net:
    name: ${APP_NAME}_network

volumes:
  mysql_data:
    name: ${APP_NAME}_mysql_data